// @generated by protobuf-ts 2.8.2 with parameter generate_dependencies,use_proto_field_name
// @generated from protobuf file "movies/v1/movie.proto" (package "movies.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * The movie message containing the title, director, and year.
 *
 * @generated from protobuf message movies.v1.Movie
 */
export interface Movie {
    /**
     * The title of the movie.
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * The director of the movie.
     *
     * @generated from protobuf field: string director = 2;
     */
    director: string;
    /**
     * The year the movie was released.
     *
     * @generated from protobuf field: int32 year = 3;
     */
    year: number;
}
/**
 * The request message containing the movie title.
 *
 * @generated from protobuf message movies.v1.GetMovieByTitleRequest
 */
export interface GetMovieByTitleRequest {
    /**
     * The title of the movie to retrieve.
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
}
/**
 * The response message containing the movie.
 *
 * @generated from protobuf message movies.v1.GetMovieByTitleResponse
 */
export interface GetMovieByTitleResponse {
    /**
     * The movie with the given title.
     *
     * @generated from protobuf field: movies.v1.Movie movie = 1;
     */
    movie?: Movie;
}
// @generated message type with reflection information, may provide speed optimized methods
class Movie$Type extends MessageType<Movie> {
    constructor() {
        super("movies.v1.Movie", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "director", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "year", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.Movie
 */
export const Movie = new Movie$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMovieByTitleRequest$Type extends MessageType<GetMovieByTitleRequest> {
    constructor() {
        super("movies.v1.GetMovieByTitleRequest", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.GetMovieByTitleRequest
 */
export const GetMovieByTitleRequest = new GetMovieByTitleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMovieByTitleResponse$Type extends MessageType<GetMovieByTitleResponse> {
    constructor() {
        super("movies.v1.GetMovieByTitleResponse", [
            { no: 1, name: "movie", kind: "message", T: () => Movie }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.GetMovieByTitleResponse
 */
export const GetMovieByTitleResponse = new GetMovieByTitleResponse$Type();
/**
 * @generated ServiceType for protobuf service movies.v1.MoviesService
 */
export const MoviesService = new ServiceType("movies.v1.MoviesService", [
    { name: "GetMovieByTitle", options: {}, I: GetMovieByTitleRequest, O: GetMovieByTitleResponse }
]);
