/* eslint-disable */
// @generated by protobuf-ts 2.8.2 with parameter long_type_string,add_pb_suffix,ts_nocheck,eslint_disable,server_grpc1,client_grpc1
// @generated from protobuf file "movies/v1/movie.proto" (package "movies.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import { MoviesService } from "./movie_pb";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { GetMovieByTitleResponse } from "./movie_pb";
import type { GetMovieByTitleRequest } from "./movie_pb";
import * as grpc from "@grpc/grpc-js";
/**
 * The movies service definition.
 *
 * @generated from protobuf service movies.v1.MoviesService
 */
export interface IMoviesServiceClient {
    /**
     * Retrieves the movie with the given title.
     *
     * @generated from protobuf rpc: GetMovieByTitle(movies.v1.GetMovieByTitleRequest) returns (movies.v1.GetMovieByTitleResponse);
     */
    getMovieByTitle(input: GetMovieByTitleRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void): grpc.ClientUnaryCall;
    getMovieByTitle(input: GetMovieByTitleRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void): grpc.ClientUnaryCall;
    getMovieByTitle(input: GetMovieByTitleRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void): grpc.ClientUnaryCall;
    getMovieByTitle(input: GetMovieByTitleRequest, callback: (err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void): grpc.ClientUnaryCall;
}
/**
 * The movies service definition.
 *
 * @generated from protobuf service movies.v1.MoviesService
 */
export class MoviesServiceClient extends grpc.Client implements IMoviesServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Retrieves the movie with the given title.
     *
     * @generated from protobuf rpc: GetMovieByTitle(movies.v1.GetMovieByTitleRequest) returns (movies.v1.GetMovieByTitleResponse);
     */
    getMovieByTitle(input: GetMovieByTitleRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetMovieByTitleResponse) => void)): grpc.ClientUnaryCall {
        const method = MoviesService.methods[0];
        return this.makeUnaryRequest<GetMovieByTitleRequest, GetMovieByTitleResponse>(`/${MoviesService.typeName}/${method.name}`, (value: GetMovieByTitleRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetMovieByTitleResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
