/* eslint-disable */
// @generated by protobuf-ts 2.8.2 with parameter long_type_string,add_pb_suffix,ts_nocheck,eslint_disable,server_grpc1,client_grpc1
// @generated from protobuf file "movies/v1/movie.proto" (package "movies.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * The movie message containing the title, director, and year.
 *
 * @generated from protobuf message movies.v1.Movie
 */
export interface Movie {
    /**
     * The title of the movie.
     *
     * @generated from protobuf field: string title = 1;
     */
    title: string;
    /**
     * The director of the movie.
     *
     * @generated from protobuf field: string director = 2;
     */
    director: string;
    /**
     * The year the movie was released.
     *
     * @generated from protobuf field: int32 year = 3;
     */
    year: number;
}
/**
 * The request message containing the movie title.
 *
 * @generated from protobuf message movies.v1.GetMovieByIdRequest
 */
export interface GetMovieByIdRequest {
    /**
     * The title of the movie to retrieve.
     *
     * @generated from protobuf field: string id = 1;
     */
    id: string;
}
/**
 * The response message containing the movie.
 *
 * @generated from protobuf message movies.v1.GetMovieByIdResponse
 */
export interface GetMovieByIdResponse {
    /**
     * The movie with the given title.
     *
     * @generated from protobuf field: movies.v1.Movie movie = 1;
     */
    movie?: Movie;
}
/**
 * The request message containing the movie.
 *
 * @generated from protobuf message movies.v1.CreateMovieRequest
 */
export interface CreateMovieRequest {
    /**
     * The movie to create.
     *
     * @generated from protobuf field: movies.v1.Movie movie = 1;
     */
    movie?: Movie;
}
/**
 * The response message containing the movie.
 *
 * @generated from protobuf message movies.v1.CreateMovieResponse
 */
export interface CreateMovieResponse {
    /**
     * The created movie.
     *
     * @generated from protobuf field: movies.v1.Movie movie = 1;
     */
    movie?: Movie;
    /**
     * @generated from protobuf field: string id = 2;
     */
    id: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class Movie$Type extends MessageType<Movie> {
    constructor() {
        super("movies.v1.Movie", [
            { no: 1, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "director", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "year", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.Movie
 */
export const Movie = new Movie$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMovieByIdRequest$Type extends MessageType<GetMovieByIdRequest> {
    constructor() {
        super("movies.v1.GetMovieByIdRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.GetMovieByIdRequest
 */
export const GetMovieByIdRequest = new GetMovieByIdRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMovieByIdResponse$Type extends MessageType<GetMovieByIdResponse> {
    constructor() {
        super("movies.v1.GetMovieByIdResponse", [
            { no: 1, name: "movie", kind: "message", T: () => Movie }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.GetMovieByIdResponse
 */
export const GetMovieByIdResponse = new GetMovieByIdResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateMovieRequest$Type extends MessageType<CreateMovieRequest> {
    constructor() {
        super("movies.v1.CreateMovieRequest", [
            { no: 1, name: "movie", kind: "message", T: () => Movie }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.CreateMovieRequest
 */
export const CreateMovieRequest = new CreateMovieRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateMovieResponse$Type extends MessageType<CreateMovieResponse> {
    constructor() {
        super("movies.v1.CreateMovieResponse", [
            { no: 1, name: "movie", kind: "message", T: () => Movie },
            { no: 2, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message movies.v1.CreateMovieResponse
 */
export const CreateMovieResponse = new CreateMovieResponse$Type();
/**
 * @generated ServiceType for protobuf service movies.v1.MoviesService
 */
export const MoviesService = new ServiceType("movies.v1.MoviesService", [
    { name: "GetMovieById", options: {}, I: GetMovieByIdRequest, O: GetMovieByIdResponse },
    { name: "CreateMovie", options: {}, I: CreateMovieRequest, O: CreateMovieResponse }
]);
