// @generated by protoc-gen-es v1.0.0 with parameter "target=js+dts"
// @generated from file movies/v1/movie.proto (package movies.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * The movie message containing the title, director, and year.
 *
 * @generated from message movies.v1.Movie
 */
export declare class Movie extends Message<Movie> {
  /**
   * The title of the movie.
   *
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * The director of the movie.
   *
   * @generated from field: string director = 2;
   */
  director: string;

  /**
   * The year the movie was released.
   *
   * @generated from field: int32 year = 3;
   */
  year: number;

  constructor(data?: PartialMessage<Movie>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "movies.v1.Movie";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Movie;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Movie;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Movie;

  static equals(a: Movie | PlainMessage<Movie> | undefined, b: Movie | PlainMessage<Movie> | undefined): boolean;
}

/**
 * The request message containing the movie title.
 *
 * @generated from message movies.v1.GetMovieByTitleRequest
 */
export declare class GetMovieByTitleRequest extends Message<GetMovieByTitleRequest> {
  /**
   * The title of the movie to retrieve.
   *
   * @generated from field: string title = 1;
   */
  title: string;

  constructor(data?: PartialMessage<GetMovieByTitleRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "movies.v1.GetMovieByTitleRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMovieByTitleRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMovieByTitleRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMovieByTitleRequest;

  static equals(a: GetMovieByTitleRequest | PlainMessage<GetMovieByTitleRequest> | undefined, b: GetMovieByTitleRequest | PlainMessage<GetMovieByTitleRequest> | undefined): boolean;
}

/**
 * The response message containing the movie.
 *
 * @generated from message movies.v1.GetMovieByTitleResponse
 */
export declare class GetMovieByTitleResponse extends Message<GetMovieByTitleResponse> {
  /**
   * The movie with the given title.
   *
   * @generated from field: movies.v1.Movie movie = 1;
   */
  movie?: Movie;

  constructor(data?: PartialMessage<GetMovieByTitleResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "movies.v1.GetMovieByTitleResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMovieByTitleResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMovieByTitleResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMovieByTitleResponse;

  static equals(a: GetMovieByTitleResponse | PlainMessage<GetMovieByTitleResponse> | undefined, b: GetMovieByTitleResponse | PlainMessage<GetMovieByTitleResponse> | undefined): boolean;
}

