// @generated by protoc-gen-es v1.0.0 with parameter "target=js+dts"
// @generated from file movies/v1/movie.proto (package movies.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * The movie message containing the title, director, and year.
 *
 * @generated from message movies.v1.Movie
 */
export const Movie = proto3.makeMessageType(
  "movies.v1.Movie",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "director", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "year", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * The request message containing the movie title.
 *
 * @generated from message movies.v1.GetMovieByTitleRequest
 */
export const GetMovieByTitleRequest = proto3.makeMessageType(
  "movies.v1.GetMovieByTitleRequest",
  () => [
    { no: 1, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * The response message containing the movie.
 *
 * @generated from message movies.v1.GetMovieByTitleResponse
 */
export const GetMovieByTitleResponse = proto3.makeMessageType(
  "movies.v1.GetMovieByTitleResponse",
  () => [
    { no: 1, name: "movie", kind: "message", T: Movie },
  ],
);

