// @generated by protoc-gen-connect-web v0.7.0
// @generated from file movies/v1/movie.proto (package movies.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMovieByTitleRequest, GetMovieByTitleResponse } from "./movie_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The movies service definition.
 *
 * @generated from service movies.v1.MoviesService
 */
export declare const MoviesService: {
  readonly typeName: "movies.v1.MoviesService",
  readonly methods: {
    /**
     * Retrieves the movie with the given title.
     *
     * @generated from rpc movies.v1.MoviesService.GetMovieByTitle
     */
    readonly getMovieByTitle: {
      readonly name: "GetMovieByTitle",
      readonly I: typeof GetMovieByTitleRequest,
      readonly O: typeof GetMovieByTitleResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

