// @generated by protoc-gen-connect-web v0.7.0
// @generated from file movies/v1/movie.proto (package movies.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetMovieByTitleRequest, GetMovieByTitleResponse } from "./movie_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * The movies service definition.
 *
 * @generated from service movies.v1.MoviesService
 */
export const MoviesService = {
  typeName: "movies.v1.MoviesService",
  methods: {
    /**
     * Retrieves the movie with the given title.
     *
     * @generated from rpc movies.v1.MoviesService.GetMovieByTitle
     */
    getMovieByTitle: {
      name: "GetMovieByTitle",
      I: GetMovieByTitleRequest,
      O: GetMovieByTitleResponse,
      kind: MethodKind.Unary,
    },
  }
};

