name: Buf PR Linting
on:
  pull_request:
    branches:
      - main
jobs:
  buf-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.NPM_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1